[Drucker]
# Logoname im Ordner Images, z.B. Logo.png
LogoName=FF Wallern.bmp
#LogoAufBon/LogoAufRechnung: True (Ja) oder False (Nein)
LogoAufBon=True
LogoAufRechnung=True
Epson=True

#in mm, z.B. 50
ZEBRA_ETI_BREITE=50
ZEBRA_ETI_HOEHE=25


[Administrator]
#PollingInterval in Sekunden, z.B. 3
PollingInterval=5

[Debug]
Mode=False
