[Drucker]
# Logoname im Ordner Images, z.B. Logo.png
LogoName=Logo.png
#LogoAufBon/LogoAufRechnung: True (Ja) oder False (Nein)
LogoAufBon=True
LogoAufRechnung=True
Epson=True


[Administrator]
#PollingInterval in Sekunden, z.B. 3
PollingInterval=5

[Feuerwehr]
Name=Feuerwehr Musterstadt
Adresse=Hauptstraﬂe 1
PLZOrt=12345 Musterstadt
Website=http://www.feuerwehr-musterstadt.at

[Debug]
Mode=False
