[Drucker]
BondruckerName=EPSON TM-T20II Receipt
EtikettenDruckerName=EPSON TM-T20II Label
# Logoname im Ordner Images, z.B. Logo.png
LogoName=Logo.png
#LogoAufBon/LogoAufRechnung: True (Ja) oder False (Nein)
LogoAufBon=True
LogoAufRechnung=True
Epson=True


[Administrator]

[Feuerwehr]
Name=Feuerwehr Musterstadt
Adresse=Hauptstraﬂe 1
PLZOrt=12345 Musterstadt
Website=http://www.feuerwehr-musterstadt.at


